[package]
name = "plume-models"
version = "0.1.0"
authors = ["Baptiste Gelez <baptiste@gelez.xyz>"]

[dependencies]
activitypub = "0.1.1"
ammonia = "1.1.0"
bcrypt = "0.2"
heck = "0.3.0"
lazy_static = "*"
openssl = "0.10.6"
reqwest = "0.8"
serde = "*"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
webfinger = "0.3"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.diesel]
features = ["postgres", "r2d2", "chrono"]
version = "*"

[dependencies.plume-common]
path = "../plume-common"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
rev = "df7111143e466c18d1f56377a8d9530a5a306aba"
